# Generated by Django 4.0.1 on 2022-10-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位列表'},
        ),
    ]
