version: "3.8"
services:
  web:
    image: "wowkingah/django-recruitment-base:0.1"
    container_name: recruitment-web
    environment:
      - server_params=--settings=settings.local
    volumes:
      - .:/data/recruitment
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - flower
  redis:
    image: "redis:alpine"
    container_name: recruit-redis
  celery:
    image: "wowkingah/django-recruitment:0.1"
    container_name: recruit-celery
    volumes:
      - .:/data/recruitment
    command: /bin/sh /data/recruitment/celery_worker_start.sh
    depends_on:
      - redis
  flower:
    image: "wowkingah/django-recruitment:0.1"
    container_name: recruit-flower
    ports:
      - "5555:5555"
    volumes:
      - .:/data/recruitment
    command: /bin/sh /data/recruitment/celery_flower_start.sh
    depends_on:
      - redis
