# Generated by Django 4.0.1 on 2022-10-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_candidate_first_interviewer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list'), ('notify', 'Notify interviewer for candidate review')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
